Repository OpenConext/OpenConext-engineblock, pull requests merged in 2019-10, with the labels that each got.

#765 Integrate metadata factory
  src/OpenConext/EngineBlock/Metadata/X509/KeyPairFactory.php
  src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
  src/OpenConext/EngineBlockBundle/Exception/EntityCanNotBeFoundException.php
  src/OpenConext/EngineBlockBundle/Metadata/MetadataFactory.php
  src/OpenConext/EngineBlockBundle/Metadata/Service/MetadataServiceInterface.php
  src/OpenConext/EngineBlockBundle/Metadata/Service/ServiceProviderMetadataService.php
  src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
  src/OpenConext/EngineBlockBundle/Resources/config/routing/metadata.yml
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  tests/unit/OpenConext/EngineBlock/Metadata/X509/KeyPairFactoryTest.php
  tests/unit/OpenConext/EngineBlockBundle/Metadata/MetadataFactoryTest.php
  theme/material/templates/modules/Authentication/View/Metadata/sp.html.twig
Labels: 6.1

#767 Remove eduGAIN support from project
  application/configs/application.ini
  bin/composer/dump-required-ini-params.sh
  library/EngineBlock/Application/DiContainer.php
  library/EngineBlock/Corto/Adapter.php
  library/EngineBlock/Corto/Mapper/Metadata/EdugainDocument.php
  library/EngineBlock/Corto/Mapper/Metadata/Entities.php
  library/EngineBlock/Corto/Mapper/Metadata/Entity.php
  library/EngineBlock/Corto/Mapper/Metadata/Entity/MdRpi/PublicationInfo.php
  library/EngineBlock/Corto/Mapper/Metadata/Entity/MdRpi/RegistrationPolicy.php
  library/EngineBlock/Corto/Module/Service/EdugainMetadata.php
  library/EngineBlock/Corto/Module/Service/IdpsMetadata.php
  library/EngineBlock/Corto/Module/Service/Metadata.php
  library/EngineBlock/Corto/ProxyServer.php
  src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
  src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
  src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
  src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepository.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/DoctrineMetadataRepository.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/InMemoryMetadataRepository.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/MetadataRepositoryInterface.php
  src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
  src/OpenConext/EngineBlockBundle/Resources/config/routing/metadata.yml
  tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsControllerTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepositoryTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/InMemoryMetadataRepositoryTest.php
Labels: 6.1

#771 Add metadata roles to template
  composer.json
  composer.lock
  src/OpenConext/EngineBlock/Metadata/X509/X509PrivateKey.php
  src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
  src/OpenConext/EngineBlockBundle/Metadata/MetadataEntityFactory.php
  src/OpenConext/EngineBlockBundle/Metadata/MetadataFactory.php
  src/OpenConext/EngineBlockBundle/Metadata/Service/MetadataService.php
  src/OpenConext/EngineBlockBundle/Metadata/Service/MetadataServiceInterface.php
  src/OpenConext/EngineBlockBundle/Metadata/ValueObjects/IdentityProviderMetadata.php
  src/OpenConext/EngineBlockBundle/Metadata/ValueObjects/ServiceProviderMetadata.php
  src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  tests/unit/OpenConext/EngineBlock/Metadata/X509/X509PrivateKeyTest.php
  tests/unit/OpenConext/EngineBlockBundle/Metadata/MetadataFactoryTest.php
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/MetadataExchange.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/oasis-200401-wss-wssecurity-secext-1.0.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/oasis-200401-wss-wssecurity-utility-1.0.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/saml-schema-assertion-2.0.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/saml-schema-metadata-2.0.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/surf.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/ws-addr.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/ws-authorization.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/ws-federation.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/ws-securitypolicy-1.2.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/xenc-schema.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/xml.xsd
  tests/unit/OpenConext/EngineBlockBundle/Metadata/schema/xmldsig-core-schema.xsd
  theme/material/templates/modules/Authentication/View/Metadata/idp.html.twig
  theme/material/templates/modules/Authentication/View/Metadata/sp.html.twig
Labels: 6.1

#768 Remove idp metadata with sp-entity-id from home
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/FrontPage.feature
  theme/material/templates/modules/Authentication/View/Index/index.html.twig
Labels: 6.1

#769 Add the application logo to the front page
  theme/material/stylesheets/application.sass
  theme/material/stylesheets/front-page.sass
  theme/material/stylesheets/front-page/base/_page.css.sass
  theme/material/stylesheets/shared/base/_layout.css.sass
  theme/material/stylesheets/shared/modules/_footer.css.sass
  theme/material/stylesheets/shared/modules/_header.css.sass
  theme/material/stylesheets/shared/utilities/_placeholders.css.sass
  theme/material/templates/modules/Authentication/View/Index/index.html.twig
Labels: 6.1

#770 Show custom error when metadata not found
  languages/messages.en.php
  languages/messages.nl.php
  languages/messages.pt.php
  src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
  src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
  src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/FrontPage.feature
  theme/material/javascripts/tests/visual-regression/error-page/ErrorPage.test.js
  theme/material/templates/modules/Authentication/View/Feedback/metadata-entity-not-found.html.twig
  theme/material/templates/modules/Authentication/View/Index/index.html.twig
Labels: 6.1

#773 Create metadata entity factory
  .travis.yml
  src/OpenConext/EngineBlock/Entities/Adapter/IdentityProviderEntity.php
  src/OpenConext/EngineBlock/Entities/Adapter/ServiceProviderEntity.php
  src/OpenConext/EngineBlock/Entities/Decorator/AbstractIdentityProvider.php
  src/OpenConext/EngineBlock/Entities/Decorator/AbstractServiceProvider.php
  src/OpenConext/EngineBlock/Entities/Decorator/IdentityProviderProxy.php
  src/OpenConext/EngineBlock/Entities/Decorator/IdentityProviderStepup.php
  src/OpenConext/EngineBlock/Entities/Decorator/ServiceProviderProxy.php
  src/OpenConext/EngineBlock/Entities/Decorator/ServiceProviderStepup.php
  src/OpenConext/EngineBlock/Entities/Factory/IdentityProviderFactory.php
  src/OpenConext/EngineBlock/Entities/Factory/ServiceProviderFactory.php
  src/OpenConext/EngineBlock/Entities/IdentityProviderEntityInterface.php
  src/OpenConext/EngineBlock/Entities/ServiceProviderEntityInterface.php
  src/OpenConext/EngineBlock/Metadata/Coins.php
  src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
  src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
  src/OpenConext/EngineBlockBundle/Controller/StepupController.php
  src/OpenConext/EngineBlockBundle/Metadata/MetadataFactory.php
  src/OpenConext/EngineBlockBundle/Metadata/Service/MetadataService.php
  src/OpenConext/EngineBlockBundle/Metadata/ValueObjects/IdentityProviderMetadataCollection.php
  src/OpenConext/EngineBlockBundle/Resources/config/routing/metadata.yml
  tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
  tests/unit/OpenConext/EngineBlockBundle/Metadata/MetadataFactoryTest.php
  theme/material/templates/modules/Authentication/View/Metadata/idps.html.twig
Labels: 6.1

#772 Implement new metadata logic to old endpoints
  src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
  src/OpenConext/EngineBlockBundle/Controller/StepupController.php
  src/OpenConext/EngineBlockBundle/Metadata/MetadataFactory.php
  src/OpenConext/EngineBlockBundle/Metadata/Service/MetadataService.php
  src/OpenConext/EngineBlockBundle/Metadata/ValueObjects/IdentityProviderMetadataCollection.php
  src/OpenConext/EngineBlockBundle/Resources/config/routing/metadata.yml
  tests/unit/OpenConext/EngineBlockBundle/Metadata/MetadataFactoryTest.php
  theme/material/templates/modules/Authentication/View/Metadata/idps.html.twig
Labels: 6.1

#778 Add missing trusted proxy to stepup callout
  library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
  library/EngineBlock/Corto/Module/Service/SingleSignOn.php
  library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
  library/EngineBlock/Corto/ProxyServer.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
Labels: 5.13, 6.0, 6.1

#775 Add missing documentation to EntityFactory
  src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntity.php
  src/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntity.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractIdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractServiceProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxy.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderStepup.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderProxy.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderStepup.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
Labels: 6.1

#781 Move the dev cache location to /tmp/eb_dev_cache
  CHANGELOG.md
  app/AppKernel.php
Labels: 6.1

#776 Display the actual EB SP/IdP metadata in the generated XML
  application/configs/application.ini
  bin/composer/dump-required-ini-params.sh
  library/EngineBlock/Application/DiContainer.php
  src/OpenConext/EngineBlock/Metadata/ContactPerson.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderMetadata.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderMetadata.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
  src/OpenConext/EngineBlock/Metadata/Factory/ValueObject/EngineBlockConfiguration.php
  src/OpenConext/EngineBlock/Service/TimeProvider/TimeProvider.php
  src/OpenConext/EngineBlock/Service/TimeProvider/TimeProviderInterface.php
  src/OpenConext/EngineBlock/Xml/DocumentSigner.php
  src/OpenConext/EngineBlock/Xml/MetadataProvider.php
  src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
  src/OpenConext/EngineBlock/Xml/ValueObjects/ServiceProviderMetadata.php
  src/OpenConext/EngineBlockBundle/Metadata/MetadataEntityFactory.php
  src/OpenConext/EngineBlockBundle/Resources/config/compat.yml
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/ValueObject/EngineBlockConfigurationTest.php
  tests/unit/OpenConext/EngineBlock/Service/TimeProvider/TimeProviderTest.php
  tests/unit/OpenConext/EngineBlock/Xml/DocumentSignerTest.php
  tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
  tests/unit/OpenConext/EngineBlock/Xml/test.pem.crt
  tests/unit/OpenConext/EngineBlock/Xml/test.pem.key
  theme/material/templates/modules/Authentication/View/Metadata/idp.html.twig
  theme/material/templates/modules/Authentication/View/Metadata/idp.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/idps.html.twig
  theme/material/templates/modules/Authentication/View/Metadata/idps.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/partial/contact_person.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/partial/organization.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/sp.html.twig
  theme/material/templates/modules/Authentication/View/Metadata/sp.xml.twig
Labels: 6.1

#783 Display the actual EB IdPs metadata in the generated XML
  library/EngineBlock/Application/DiContainer.php
  library/EngineBlock/Corto/Adapter.php
  library/EngineBlock/Corto/ProxyServer.php
  src/OpenConext/EngineBlock/Exception/ServiceReplacingException.php
  src/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntity.php
  src/OpenConext/EngineBlock/Metadata/Factory/Collection/IdentityProviderEntityCollection.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractIdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderMetadata.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderMetadata.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxy.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
  src/OpenConext/EngineBlock/Metadata/Factory/IdentityProviderEntityInterface.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
  src/OpenConext/EngineBlock/Service/Metadata/ServiceReplacer.php
  src/OpenConext/EngineBlock/Xml/MetadataProvider.php
  src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
  src/OpenConext/EngineBlock/Xml/ValueObjects/IdentityProviderMetadataCollection.php
  src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
  src/OpenConext/EngineBlockBundle/Exception/UnableToCreateUrlException.php
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  src/OpenConext/EngineBlockBundle/Url/UrlProvider.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
  tests/library/EngineBlock/Test/Corto/Module/Service/ProvideConsentTest.php
  tests/library/EngineBlock/Test/Corto/ProxyServerTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
  tests/unit/OpenConext/EngineBlock/Service/Metadata/ServiceReplacerTest.php
  tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
  tests/unit/OpenConext/EngineBlockBundle/Url/UrlProviderTest.php
  theme/material/templates/modules/Authentication/View/Metadata/idp.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/idps.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/partial/shibmd_scope.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/sp.xml.twig
Labels: 6.1

#789 Address issue PR 787 788
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxy.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/AbstractEntityTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxyTest.php
  theme/material/templates/modules/Authentication/View/Metadata/idp.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/idps.xml.twig
Labels: 6.1, wip

#792 Update puppeteer-core after audit
  theme/package-lock.json
Labels: 6.0, 6.1

#793 Update ChromeDriver to match Chrome version
  .travis.yml
Labels: 6.0, 6.1

#785 Render the terms of use in the XML metadata
  src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
  theme/material/templates/modules/Authentication/View/Metadata/idp.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/idps.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/sp.xml.twig
Labels: 6.1

#791 Show service info if no attributes are set (twig)
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderInformation.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderInformation.php
  tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
  theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
  theme/material/templates/modules/Authentication/View/Metadata/sp.xml.twig
Labels: 6.1

#799 Added IDPentityID to the Attribute Aggregation request
  library/EngineBlock/Corto/Filter/Command/AttributeAggregator.php
  src/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/Request.php
  tests/library/EngineBlock/Test/Corto/Filter/Command/AttributeAggregatorTest.php
  tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/AttributeAggregationClientTest.php
  tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/RequestTest.php
Labels: 6.0
