Repository OpenConext/OpenConext-engineblock, pull requests merged in 2019-11, with the labels that each got.

#802 Implement countermeasures against CVE 2019-3465
  CHANGELOG.md
  composer.lock
Labels: 6.0

#803 Implement countermeasures against CVE 2019-3465
  .travis.yml
  CHANGELOG.md
  composer.lock
Labels: 5.13

#805 Upgrade handlebars to 4.5.1
  theme/package-lock.json
Labels: 6.0

#804 Stop disasembling the Edugain publication settings
  src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
Labels: 6.1

#798 Remove ResponseProcessingService
  library/EngineBlock/Corto/Adapter.php
  library/EngineBlock/Corto/ProxyServer.php
  src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
  src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntity.php
  src/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntity.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractIdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractServiceProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxy.php
  src/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadata.php
  src/OpenConext/EngineBlock/Metadata/Factory/IdentityProviderEntityInterface.php
  src/OpenConext/EngineBlock/Metadata/Factory/ServiceProviderEntityInterface.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/Visitor/EngineBlockMetadataVisitor.php
  src/OpenConext/EngineBlock/Stepup/StepupEntityFactory.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/AbstractEntityTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntityTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntityTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxyTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
Labels: 6.1

#797 Use correct language value in organization metadata
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderStepup.php
  src/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockIdentityProviderMetadata.php
  src/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadata.php
  src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockIdentityProviderMetadataTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadataTest.php
  tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
  theme/material/templates/modules/Authentication/View/Metadata/partial/organization.xml.twig
Labels: 6.1

#796 Adjust decorator naming to reflect purpose
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderInformation.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderInformation.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
  src/OpenConext/EngineBlock/Metadata/Factory/Helper/IdentityProviderMetadataHelper.php
  src/OpenConext/EngineBlock/Metadata/Factory/Helper/ServiceProviderMetadataHelper.php
  src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockIdentityProviderTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockIdentityProviderMetadataTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadataTest.php
  tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
Labels: 6.1

#809 Fix typos for stepup no token
  languages/messages.en.php
Labels: 6.0

#808 Update symfony/mime dependency to pass build
  composer.lock
Labels: 6.0

#800 Reconfigure LoA settings and verify received LoA
  application/configs/application.ini
  library/EngineBlock/Application/DiContainer.php
  library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
  library/EngineBlock/Corto/Module/Services.php
  library/EngineBlock/Corto/ProxyServer.php
  src/OpenConext/EngineBlock/Exception/LoaNotFoundException.php
  src/OpenConext/EngineBlock/Metadata/Loa.php
  src/OpenConext/EngineBlock/Metadata/LoaRepository.php
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  src/OpenConext/EngineBlockBundle/Stepup/StepupDecision.php
  src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayCallOutHelper.php
  src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMapping.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/StepupMockController.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/StepupContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
  tests/unit/OpenConext/EngineBlock/Metadata/LoaRepositoryTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/LoaTest.php
  tests/unit/OpenConext/EngineBlockBundle/Stepup/StepupDecisionTest.php
  tests/unit/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMappingTest.php
Labels: 6.0

#813 Upgrade Symfony to 3.4.35
  composer.lock
Labels: 6.1, security

#814 Upgrade Handlebars to 4.5.3
  theme/package-lock.json
Labels: 6.1, security

#810 Prevent double schema and hostname on logo
  src/OpenConext/EngineBlock/Metadata/Factory/ValueObject/EngineBlockConfiguration.php
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockIdentityProviderInformationTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockServiceProviderInformationTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/ValueObject/EngineBlockConfigurationTest.php
  theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
Labels: 6.1

#815 Fix broken ProxiedIdentityProvider test
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProviderTest.php
Labels: 6.1

#812 Provide Metadata documentation
  docs/metadata_decorators.md
  docs/metadata_generation.md
  docs/metadata_generation.png
Labels: 6.1

#816 Prevent mem denial of service vulnerability
  theme/package-lock.json
Labels: 6.1

#817 Remove migration to support 5.13
  database/DoctrineMigrations/Version20190710141146.php
Labels: 6.0

#819 Prevent invalid assertion when stepup LoA is set
  .travis.yml
  app/config/config_test.yml
  library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
  src/OpenConext/EngineBlock/Metadata/Loa.php
Labels: 6.0, 6.1

#811 Remove unused metadata entities and logic
  CHANGELOG.md
  UPGRADING.md
  library/EngineBlock/Application/DiContainer.php
  library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
  library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
  library/EngineBlock/Corto/Module/Service/IdpsMetadata.php
  library/EngineBlock/Corto/Module/Service/Metadata.php
  library/EngineBlock/Corto/Module/Service/Metadata/ArpRequestedAttributes.php
  library/EngineBlock/Corto/Module/Service/SingleSignOn.php
  library/EngineBlock/Corto/Module/Services.php
  src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Debug.feature
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/LocaleSelection.feature
Labels: 6.1

#820 Fix namespace after cherry picked bugfix
  .travis.yml
  composer.lock
  library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
  theme/package-lock.json
Labels: 6.0
