Repository OpenConext/OpenConext-engineblock, pull requests merged in 2019-09, with the labels that each got.

#753 Improve 5.11 installation instructions
  UPGRADING.md
  app/config/parameters.yml.dist
Labels: 5.11

#752 Store coin properties in a single column
  .travis.yml
  CHANGELOG.md
  UPGRADING.md
  app/config/config.yml
  composer.json
  composer.lock
  database/DoctrineMigrations/Version20190703235333.php
  library/EngineBlock/Corto/Adapter.php
  library/EngineBlock/Corto/Filter/Command/AddGuestStatus.php
  library/EngineBlock/Corto/Filter/Command/DenormalizeAttributes.php
  library/EngineBlock/Corto/Filter/Command/EnforcePolicy.php
  library/EngineBlock/Corto/Filter/Command/ValidateRequiredAttributes.php
  library/EngineBlock/Corto/Module/Bindings.php
  library/EngineBlock/Corto/Module/Service/IdpsMetadata.php
  library/EngineBlock/Corto/Module/Service/ProvideConsent.php
  library/EngineBlock/Corto/Module/Service/SingleSignOn.php
  library/EngineBlock/Corto/ProxyServer.php
  library/EngineBlock/Saml2/AuthnRequestFactory.php
  library/EngineBlock/SamlHelper.php
  src/OpenConext/EngineBlock/Authentication/Dto/Consent.php
  src/OpenConext/EngineBlock/Metadata/Coins.php
  src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
  src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
  src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
  src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/InMemoryMetadataRepository.php
  src/OpenConext/EngineBlockBundle/Doctrine/Type/MetadataCoinType.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
  tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsControllerTest.php
  tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConsentControllerTest.php
  tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
  tests/library/EngineBlock/Test/Corto/Module/Service/ProvideConsentTest.php
  tests/unit/OpenConext/EngineBlock/Authentication/Dto/ConsentTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassemblerTest.php
Labels: 5.12

#755 Cleanup old coin columns
  database/DoctrineMigrations/Version20190710141146.php
  src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
  src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
Labels: 6.0

#756 Get termsOfServiceUrl from coins, not SP metadata entity
  theme/material/templates/modules/Authentication/View/Proxy/consent.html.twig
Labels: 6.0

#713 PHP 7.2 compatibility changes
  .travis.yml
  library/EngineBlock/Application/ErrorHandler.php
  library/EngineBlock/ApplicationSingleton.php
  src/OpenConext/EngineBlockBundle/Exception/Art.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Consent.feature
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
Labels: 6.0

#760 Prevent WAYF c-button from floating left
  theme/material/stylesheets/application/modules/_results.css.sass
Labels: 6.0

#759 Use twig to build metadata
  src/OpenConext/EngineBlockBundle/Metadata/MetadataFactory.php
  tests/functional/OpenConext/EngineBlockBundle/Controller/Api/MetadataControllerTest.php
  tests/unit/OpenConext/EngineBlockBundle/Metadata/MetadataFactoryTest.php
  theme/material/templates/modules/Authentication/View/Metadata/idp.html.twig
  theme/material/templates/modules/Authentication/View/Metadata/sp.html.twig
Labels: 6.1

#764 Upgrade Doctrine ORM to version 2.6
  composer.json
  composer.lock
  src/OpenConext/EngineBlock/Metadata/AttributeReleasePolicy.php
  src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
  src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
  src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/I18n.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/IdentityProviderController.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/AbstractMockEntityFactory.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/EntityRegistry.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProviderFactory.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Saml2/Compat/Container.php
Labels: 6.1

#763 Update Composer for improved PHP 7.2 support
  composer.json
  composer.lock
  src/OpenConext/EngineBlock/Metadata/AttributeReleasePolicy.php
  src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
  src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
  src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/I18n.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/IdentityProviderController.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/AbstractMockEntityFactory.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/EntityRegistry.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProviderFactory.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Saml2/Compat/Container.php
Labels: 6.0

#762 Update changelog, readme, and the upgrading notes
  CHANGELOG.md
  README.md
  UPGRADING.md
Labels: 6.0
