Repository OpenConext/OpenConext-engineblock, pull requests merged in 2020-09, with the labels that each got.

#889 Store entityId of issuer, not the value object
  library/EngineBlock/ApplicationSingleton.php
  library/EngineBlock/Corto/Model/Response/Cache.php
  library/EngineBlock/Corto/Module/Bindings.php
Labels: 6.3.2

#890 Move NoPassive response processing up in the ACS proces
  library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
Labels: 6.3.3

#891 Print the key-id in the SSO locations of the IdP metadata
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProvider.php
  src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
  src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
  src/OpenConext/EngineBlock/Metadata/X509/KeyPairFactory.php
  src/OpenConext/EngineBlock/Xml/MetadataProvider.php
  src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
  src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockIdentityProviderTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProviderTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
Labels: 6.3.3

#892 Upgrade jpeg-js to v0.4.0
  theme/package-lock.json
  theme/package.json
Labels: 6.3.3

#894 Test whether MFA AuthnContext must be added should be based on original SP
  CHANGELOG.md
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthnContextClassRef.feature
Labels: 6.3.4

#898 Clean up unused usage of authnrequest destination
  library/EngineBlock/Corto/Module/Bindings.php
  library/EngineBlock/Exception/UnknownServiceProvider.php
  src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
Labels: 6.3.5

#899 Add support for mobile devices on consent page
  languages/messages.en.php
  theme/.browserslistrc
  theme/README.md
  theme/base/stylesheets/a11y-tests.scss
  theme/base/stylesheets/breakpoints.scss
  theme/base/stylesheets/classes.scss
  theme/base/stylesheets/helpers.scss
  theme/base/stylesheets/mixins.scss
  theme/base/stylesheets/pages/consent.scss
  theme/base/stylesheets/shared.scss
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/engineBlockAttribute.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/name.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/tooltip.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/value.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/disclaimerList.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
  theme/base/templates/modules/Default/Partials/footer.html.twig
  theme/base/templates/modules/Default/Partials/toggleCheckbox.html.twig
  theme/cypress/integration/consent/a11y.spec.js
  theme/skeune/stylesheets/breakpoints.scss
  theme/skeune/stylesheets/helpers.scss
  theme/skeune/templates/modules/Default/Partials/label.html.twig
Labels: ui-redesign

#902 Refactor the html for the WAYF in the base theme
  languages/messages.en.php
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/header.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/header.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idpList.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/ctas.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/helpdesk.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/noAccess.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/requestForm.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noresults.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noscript.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/rememberChoice.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/scriptConfig.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/consent.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/wayf.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/wayf_content.html.twig
  theme/base/templates/modules/Default/Partials/informational.html.twig
Labels: ui-redesign, wayf

#901 Add the extra notification to the consent page
  languages/messages.en.php
  theme/base/stylesheets/classes.scss
  theme/base/stylesheets/mixins.scss
  theme/base/stylesheets/pages/consent.scss
  theme/base/stylesheets/shared.scss
  theme/base/stylesheets/variables.scss
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/attention.svg
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/extraNotification.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/consent.html.twig
Labels: ui-redesign

#903 Break up Cypress tests for different themes
  .github/workflows/test-integration.yml
  theme/.editorconfig
  theme/README.md
  theme/cypress/integration/openconext/consent/consent.material.spec.js
  theme/cypress/integration/openconext/wayf/UnconnectedIdpPicker.spec.js
  theme/cypress/integration/openconext/wayf/WayfMouseBehaviour.spec.js
  theme/cypress/integration/openconext/wayf/WayfShowsConnectedIdps.spec.js
  theme/cypress/integration/skeune/consent/a11y.spec.js
  theme/cypress/integration/skeune/consent/consent.skeune.spec.js
  theme/cypress/support/commands.js
  theme/scripts/build.js
  theme/scripts/create-theme.js
  theme/scripts/prepare-test.js
Labels: ui-redesign
