Repository OpenConext/OpenConext-engineblock, pull requests merged in 2021-04, with the labels that each got.

#1102 Fix missing titles in functional tests
  src/OpenConext/EngineBlockFunctionalTestingBundle/Helper/TestEntitySeeder.php
Labels: bug, wayf

#1097 Ensure logout page is styled for skeune
  theme/README.md
  theme/base/stylesheets/application.scss
  theme/base/stylesheets/pages/form.scss
  theme/base/stylesheets/pages/logout.scss
  theme/base/stylesheets/shared.scss
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/header.html.twig
  theme/base/templates/modules/Logout/View/Index/index.html.twig
  theme/cypress/integration/shared/logout.a11y.spec.js
  theme/skeune/stylesheets/application.scss
Labels: bug, ui-redesign

#1099 WAYF a11y improvements
  theme/base/javascripts/handlers.js
  theme/base/javascripts/selectors.js
  theme/base/javascripts/utility/hideElementNoTab.js
  theme/base/javascripts/utility/showElementAlsoTab.js
  theme/base/javascripts/wayf/deleteDisable/deleteIdp.js
  theme/base/javascripts/wayf/handleClickingDisabledIdp.js
  theme/base/javascripts/wayf/handleDeleteDisable.js
  theme/base/javascripts/wayf/mouseBehaviour.js
  theme/base/javascripts/wayf/noAccess/attachClickHandlerToForm.js
  theme/base/javascripts/wayf/noAccess/cancelButtonClickHandler.js
  theme/base/javascripts/wayf/noAccess/hideNoAccess.js
  theme/base/javascripts/wayf/noAccess/showSuccessMessage.js
  theme/base/javascripts/wayf/noAccess/validation.js
  theme/base/javascripts/wayf/search/showOrHideNoResultsSection.js
  theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
  theme/base/stylesheets/components/success.scss
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpDeleteDisable.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/helpdesk.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/noAccess.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/requestForm.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/successMessage.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noResults.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
  theme/base/templates/modules/Default/Partials/informational.html.twig
  theme/base/templates/modules/Default/Partials/success.html.twig
  theme/skeune/translations/messages.en.php
  theme/skeune/translations/messages.nl.php
  theme/skeune/translations/messages.pt.php
Labels: bug, ui-redesign, wayf

#1107 Remove forgotten debug statement
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpDeleteDisable.html.twig
Labels: 6.6, bug, wayf

#1110 Remove double titles on skeune error pages
  theme/base/templates/modules/Authentication/View/Feedback/authn-context-class-ref-blacklisted.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/clock-issue.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/custom.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/invalid-acs-binding.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/invalid-acs-location.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/invalid-attribute-value.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/invalid-mfa-authn-context-class-ref.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/metadata-entity-not-found.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/missing-required-fields.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/no-authentication-request-received.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/no-idps.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/received-error-status-code.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/received-invalid-response.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/received-invalid-signed-response.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/session-lost.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/session-not-started.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/stepup-callout-unknown.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/stepup-callout-unmet-loa.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/stepup-callout-user-cancelled.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/stuck-in-authentication-loop.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unable-to-receive-message.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-error.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-identity-provider.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-preselected-idp.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-requesterid-in-authnrequest.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unsupported-acs-location-scheme.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unsupported-signature-method.html.twig
Labels: 6.6, bug, error-handling, ui-redesign

#1108 Include Twig linting in CI pipeline
  .github/workflows/test-integration.yml
  README.md
  build.xml
  docs/php_testing.md
Labels: 6.6, enhancement

#1105 Allow AuthnRequest based stepup requests
  library/EngineBlock/Application/DiContainer.php
  library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
  library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
  library/EngineBlock/Saml2/AuthnRequestAnnotationDecorator.php
  src/OpenConext/EngineBlock/Metadata/LoaRepository.php
  src/OpenConext/EngineBlock/Stepup/StepupDecision.php
  src/OpenConext/EngineBlock/Stepup/StepupGatewayCallOutHelper.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
  tests/library/EngineBlock/Test/Saml2/AuthnRequestAnnotationDecoratorTest.php
  tests/unit/OpenConext/EngineBlock/Metadata/LoaRepositoryTest.php
  tests/unit/OpenConext/EngineBlock/Stepup/StepupDecisionTest.php
Labels: 6.6

#1113 Use "account" instead of organisation
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Debug.feature
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
  theme/cypress/integration/skeune/wayf/wayf.general.spec.js
  theme/skeune/translations/messages.en.php
  theme/skeune/translations/messages.nl.php
Labels: 6.6, bug

#1115 Adjust php version in the twig linting script
  .github/workflows/test-integration.yml
Labels: bug

#1116 Replace the hamburger and search icon
  theme/base/images/burger.svg
  theme/base/images/search.svg
  theme/base/images/user.svg
  theme/openconext/stylesheets/application/modules/_app-search.css.sass
  theme/openconext/templates/layouts/scripts/default.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/wayf.html.twig
  theme/openconext/templates/modules/Default/View/Error/partial/legacy_header.html.twig
  theme/openconext/translations/messages.en.php
  theme/openconext/translations/messages.nl.php
  theme/openconext/translations/messages.pt.php
Labels: 6.6, enhancement

#1112 Clarify skeune error messages
  languages/messages.en.php
  languages/messages.nl.php
  languages/messages.pt.php
  library/EngineBlock/ApplicationSingleton.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/FeedbackController.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/FeedbackFooters.feature
  theme/base/templates/modules/Authentication/View/Feedback/authn-context-class-ref-blacklisted.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/clock-issue.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/invalid-attribute-value.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/invalid-mfa-authn-context-class-ref.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/missing-required-fields.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/no-idps.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/received-invalid-response.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/received-invalid-signed-response.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/stuck-in-authentication-loop.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-error.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-identity-provider.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-preselected-idp.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
  theme/base/templates/modules/Default/View/Error/error.html.twig
  theme/cypress/integration/skeune/error/error.general.spec.js
Labels: 6.6, enhancement, error-handling

#1130 Adjust openconext error messages
  languages/messages.en.php
  languages/messages.nl.php
  theme/openconext/templates/modules/Authentication/View/Feedback/authn-context-class-ref-blacklisted.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/clock-issue.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/invalid-attribute-value.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/invalid-mfa-authn-context-class-ref.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/missing-required-fields.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/no-idps.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/received-invalid-response.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/received-invalid-signed-response.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/stuck-in-authentication-loop.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/unknown-error.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/unknown-identity-provider.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/unknown-preselected-idp.html.twig
  theme/openconext/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
  theme/openconext/templates/modules/Default/View/Error/error.html.twig
Labels: 6.6, enhancement, error-handling

#1128 Add a global site notice
  app/config/config_test.yml
  app/config/parameters.yml.dist
  languages/messages.en.php
  languages/messages.nl.php
  languages/messages.pt.php
  src/OpenConext/EngineBlockBundle/Controller/WayfController.php
  src/OpenConext/EngineBlockBundle/Resources/config/services.yml
  src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/FunctionalTestingGlobalSiteNotice.php
  src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/GlobalSiteNotice.php
  src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/GlobalSiteNoticeInterface.php
  theme/README.md
  theme/base/javascripts/selectors.js
  theme/base/stylesheets/components/old-not-converted/button.scss
  theme/base/stylesheets/components/old-not-converted/content.scss
  theme/base/stylesheets/components/old-not-converted/footer.scss
  theme/base/stylesheets/components/old-not-converted/language.scss
  theme/base/stylesheets/components/old-not-converted/layout.scss
  theme/base/stylesheets/components/old-not-converted/page.scss
  theme/base/stylesheets/components/old-not-converted/warning.scss
  theme/base/stylesheets/components/warning.scss
  theme/base/stylesheets/pages/notConverted.scss
  theme/base/stylesheets/variables.scss
  theme/base/templates/modules/Authentication/View/IdentityProvider/remove-cookies.html.twig
  theme/base/templates/modules/Authentication/View/Index/index.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/consentContent.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/site-notice.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/wayf_content.html.twig
  theme/base/templates/modules/Default/Partials/notConverted/header.html.twig
  theme/base/templates/modules/Default/Partials/warning.html.twig
  theme/base/templates/modules/Logout/View/Index/index.html.twig
  theme/cypress/integration/shared/cookieRemoval.a11y.spec.js
  theme/cypress/integration/skeune/consent/consent.general.spec.js
  theme/cypress/integration/skeune/index/index.general.spec.js
  theme/cypress/integration/skeune/wayf/wayf.general.spec.js
  theme/openconext/stylesheets/application.sass
  theme/openconext/stylesheets/application/components/_warning.css.sass
  theme/openconext/stylesheets/application/modules/_consent.css.sass
  theme/openconext/stylesheets/front-page.scss
  theme/openconext/templates/modules/Authentication/View/IdentityProvider/remove-cookies.html.twig
  theme/openconext/templates/modules/Authentication/View/Index/index.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/site-notice.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/wayf.html.twig
  theme/openconext/templates/modules/Logout/View/Index/index.html.twig
  theme/skeune/stylesheets/mixins-skeune.scss
Labels: 6.6, consent, enhancement, wayf
