Repository OpenConext/OpenConext-engineblock, pull requests merged in 2021-01, with the labels that each got.

#1049 Repair the quirky behavior whilst theme switching
  README.md
  app/config/config_dev.yml
  app/config/functional_testing.yml.dist
Labels: ui-redesign

#1047 Optimize consent screenreader support
  theme/base/javascripts/consent/addA11ySupport.js
  theme/base/javascripts/consent/addInteractiveAriaHandlers.js
  theme/base/javascripts/consent/addTooltipAndModalAriaHandlers.js
  theme/base/javascripts/consent/enterHandler.js
  theme/base/javascripts/consent/switchConsentSection.js
  theme/base/javascripts/handlers.js
  theme/base/javascripts/selectors.js
  theme/base/javascripts/utility/changeAriaHiddenValue.js
  theme/base/stylesheets/mixins.scss
  theme/base/stylesheets/pages/consent/attribute.scss
  theme/base/stylesheets/pages/consent/attributeValue.scss
  theme/base/stylesheets/pages/consent/openToggle.scss
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/engineBlockAttribute.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/name.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/tooltip.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Modals/correction.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Modals/reject.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/nokSection.html.twig
  theme/cypress/functions/terminalLog.js
  theme/cypress/integration/skeune/consent/consent.general.spec.js
  theme/cypress/integration/skeune/consent/consent.keyboard.spec.js
  theme/cypress/integration/skeune/consent/consent.mouse.spec.js
  theme/skeune/translations/messages.en.php
  theme/skeune/translations/messages.nl.php
  theme/skeune/translations/messages.pt.php
Labels: consent, ui-redesign

#1050 Expand consent linguistics
  languages/messages.en.php
  languages/messages.nl.php
  languages/messages.pt.php
  library/EngineBlock/Corto/Module/Service/ProvideConsent.php
  src/OpenConext/EngineBlock/Metadata/ConsentSettings.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/ConsentController.php
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Consent.feature
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
  tests/unit/OpenConext/EngineBlock/Metadata/ConsentSettingsTest.php
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/consent.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
  theme/skeune/translations/messages.en.php
  theme/skeune/translations/messages.nl.php
  theme/skeune/translations/messages.pt.php
Labels: consent, ui-redesign

#1053 Change translation as requested
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
  theme/skeune/translations/messages.en.php
  theme/skeune/translations/messages.nl.php
  theme/skeune/translations/messages.pt.php
Labels: bug, ui-redesign, wayf

#1052 Clean up design index page
  theme/base/stylesheets/front-page.sass
  theme/base/stylesheets/front-page.scss
  theme/base/stylesheets/front-page/base/_page.sass
  theme/base/stylesheets/front-page/modules/_container.sass
  theme/base/stylesheets/front-page/modules/_footer.sass
  theme/base/stylesheets/front-page/modules/_header.sass
  theme/base/stylesheets/pages/front-page.sass
  theme/base/stylesheets/pages/front-page.scss
  theme/base/stylesheets/pages/front-page/modules/container.scss
  theme/base/stylesheets/pages/front-page/modules/footer.scss
  theme/base/stylesheets/pages/front-page/modules/header.scss
  theme/base/stylesheets/pages/front-page/page.scss
  theme/base/stylesheets/variables.scss
  theme/base/templates/modules/Authentication/View/Index/index.html.twig
  theme/openconext/stylesheets/front-page.scss
  theme/skeune/stylesheets/front-page.scss
Labels: ui-redesign

#1054 Ensure links have enough contrast
  theme/base/stylesheets/pages/front-page/modules/footer.scss
  theme/base/stylesheets/pages/front-page/page.scss
Labels: bug, ui-redesign

#1055 Style debug page
  theme/base/stylesheets/components/old-not-converted/button.scss
  theme/base/stylesheets/components/old-not-converted/container.scss
  theme/base/stylesheets/components/old-not-converted/content.scss
  theme/base/stylesheets/components/old-not-converted/fontAwesome.scss
  theme/base/stylesheets/components/old-not-converted/footer.scss
  theme/base/stylesheets/components/old-not-converted/header.scss
  theme/base/stylesheets/components/old-not-converted/icon.scss
  theme/base/stylesheets/components/old-not-converted/language.scss
  theme/base/stylesheets/components/old-not-converted/layout.scss
  theme/base/stylesheets/components/old-not-converted/links.scss
  theme/base/stylesheets/components/old-not-converted/page.scss
  theme/base/stylesheets/components/old-not-converted/table.scss
  theme/base/stylesheets/debug-page.scss
  theme/base/stylesheets/error-page.sass
  theme/base/stylesheets/error-page.scss
  theme/base/stylesheets/fonts.scss
  theme/base/stylesheets/pages/debug.scss
  theme/base/stylesheets/pages/debug/overwrites.scss
  theme/base/stylesheets/pages/front-page.scss
  theme/base/stylesheets/variables.scss
  theme/base/templates/layouts/scripts/default.html.twig
  theme/base/templates/modules/Authentication/View/Index/index.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
  theme/openconext/stylesheets/application.sass
  theme/openconext/stylesheets/error-page.scss
  theme/skeune/stylesheets/debug-page.scss
  theme/skeune/stylesheets/error-page.scss
  theme/skeune/translations/messages.en.php
  theme/skeune/translations/messages.nl.php
  theme/skeune/translations/messages.pt.php
  web/fonts/.gitkeep
Labels: ui-redesign

#1057 Style cookie page
  features/bootstrap/FeatureContext.php
  theme/base/stylesheets/components/old-not-converted/header.scss
  theme/base/stylesheets/components/old-not-converted/language.scss
  theme/base/stylesheets/debug-page.scss
  theme/base/stylesheets/material.scss
  theme/base/stylesheets/pages/debug/overwrites.scss
  theme/base/stylesheets/pages/notConverted.scss
  theme/base/templates/layouts/scripts/notConverted.twig
  theme/base/templates/modules/Authentication/View/IdentityProvider/remove-cookies.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
  theme/base/templates/modules/Default/Partials/notConverted/footer.html.twig
  theme/base/templates/modules/Default/Partials/notConverted/header.html.twig
  theme/skeune/stylesheets/debug-page.scss
  theme/skeune/stylesheets/material.scss
Labels: ui-redesign

#1058 Style index page in material theme
  theme/openconext/stylesheets/front-page.scss
Labels: bug, ui-redesign

#1059 Fix four-oh-fours on tippy styles
  theme/openconext/stylesheets/application.sass
  theme/package.json
Labels: bug, ui-redesign

#1051 Performance and compatibility improvements
  theme/base/templates/layouts/scripts/default.html.twig
  theme/base/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
  theme/base/templates/modules/Authentication/View/Index/index.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/spinner.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
  theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
  theme/openconext/templates/layouts/scripts/default.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/form.html.twig
  theme/openconext/templates/modules/Authentication/View/Proxy/wayf.html.twig
  theme/openconext/templates/modules/Default/View/Error/partial/legacy_header.html.twig
Labels: ui-redesign

#1066 Ensure hitting reset shows default idp
  theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
  theme/cypress/integration/skeune/wayf/wayf.general.spec.js
Labels: bug, ui-redesign, wayf

#1067 Ensure clicking the defaultIdp works correctly
  theme/base/javascripts/selectors.js
  theme/base/javascripts/utility/fireClickEvent.js
  theme/base/javascripts/wayf/handleIdpBanner.js
Labels: bug, ui-redesign, wayf

#1069 Remove weird transition in safari
  theme/base/stylesheets/pages/wayf/previousSelection.scss
  theme/base/stylesheets/pages/wayf/remainingIdps.scss
Labels: bug, ui-redesign, wayf

#1070 Redesign the spinner page
  theme/README.md
  theme/base/stylesheets/components.scss
  theme/base/stylesheets/components/spinner.scss
  theme/base/stylesheets/pages/form.scss
  theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
  theme/skeune/translations/messages.en.php
  theme/skeune/translations/messages.nl.php
  theme/skeune/translations/messages.pt.php
Labels: ui-redesign

#1073 Add a hover style for the disabled accounts
  theme/base/stylesheets/pages/wayf/idpList.scss
  theme/skeune/stylesheets/mixins-skeune.scss
Labels: bug, consent

#1071 Fix IE11 bugs with search
  src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
  theme/base/javascripts/handlers.js
  theme/base/javascripts/selectors.js
  theme/base/javascripts/utility/nodeListToArray.js
  theme/base/javascripts/wayf/deleteDisable/deleteIdp.js
  theme/base/javascripts/wayf/handleIdpBanner.js
  theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
  theme/base/javascripts/wayf/utility/sortArrayList.js
  theme/base/javascripts/wayf/utility/switchIdpSection.js
  theme/base/stylesheets/pages/wayf/remainingIdps.scss
  theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
  theme/package.json
Labels: bug, ui-redesign, wayf

#1068 Ensure hitting the arrow works as expected
  theme/base/javascripts/selectors.js
  theme/base/javascripts/utility/focusAndSmoothScroll.js
  theme/base/javascripts/wayf/idpFocus/arrowDown.js
  theme/base/javascripts/wayf/idpFocus/arrowUp.js
  theme/base/javascripts/wayf/idpFocus/checkHover.js
  theme/base/javascripts/wayf/idpFocus/focusOnNextIdp.js
  theme/base/javascripts/wayf/idpFocus/focusOnPreviousIdp.js
  theme/base/javascripts/wayf/idpFocus/isFocusOnArrowItem.js
  theme/base/javascripts/wayf/idpFocus/isHoverOnArrowItem.js
  theme/base/javascripts/wayf/keyboardBehaviour.js
  theme/base/javascripts/wayf/mouseBehaviour.js
  theme/base/javascripts/wayf/search/assignWeight.js
  theme/base/javascripts/wayf/search/toggleDefaultIdPLinkVisibility.js
Labels: bug, ui-redesign, wayf

#1072 Couple cypress tests to same selectors
  theme/base/javascripts/selectors.js
  theme/cypress/integration/skeune/consent/consent.general.spec.js
  theme/cypress/integration/skeune/consent/consent.keyboard.spec.js
  theme/cypress/integration/skeune/consent/consent.mouse.spec.js
  theme/cypress/integration/skeune/error/error.general.spec.js
  theme/cypress/integration/skeune/index/index.general.spec.js
  theme/cypress/integration/skeune/testSelectors.js
  theme/cypress/integration/skeune/wayf/wayf.general.spec.js
  theme/cypress/integration/skeune/wayf/wayf.keyboard.spec.js
  theme/cypress/integration/skeune/wayf/wayf.mouse.spec.js
Labels: consent, ui-redesign, wayf
